### ISSUE TITLE
cpuMemRelation

### ISSUE THREAD

**Issue by marianobilli** [empathyco/kubernetes-cost-report#30]
First of all, great project! 

I just wanted to ask you what was the rationale to choose cpuMemRelation = 7.2, which somehow ends up with memory having "bigger weight" o the price.

I was wandering why not assign half of the price to mem and half to cpu
```
MemPrice = ( p.Price / 2 ) / float64(p.GetMemory())
CPUPrice = ( p.Price / 2 ) / float64(p.GetCPU())
```

Thanks!

**Comment by cesarempathy** [comment]
Hi @marianobilli, as you probably know, CPU usage is more expensive than RAM, you only need to check the processor prices vs the ram prices.
But the reason why we have used a factor of 7.2 is that Google uses that factor when calculating the unit price relation between CPU and RAM.  
To check that you only can do a small operation, 
The CPU unit price at Google is 0.023993 and the RAM unit price is 0.007198.
So, if we do the math. 

```sh
# cpuMemRelation=cpuUnitPrice/memUnitPrice
# cpuMemRelation=0.023993/0.003216
bc -l <<< "0.023993/0.003216"
7.46050995024875621890
```

That means that the CPU unit price is around 7.4 times  (when we did the calculation 6 months ago was 7.2) more expense than the RAM unit prices (a GB of RAM).

We have supposed that this rule can be applied to other cloud providers.

Hope this help.

GCP prices: https://cloud.google.com/compute/vm-instance-pricing

**Comment by marianobilli** [comment]
I didn't know that! thanks for the answer!
