### ISSUE TITLE
Data transfer charges?

### ISSUE THREAD

**Issue by chainhead** [empathyco/kubernetes-cost-report#35]
How do we track inter AZ, internet ingress data  charges at pod level?

**Comment by kaskol10** [comment]
Thanks for your question @chainhead! Sorry for the late answer, by now, this project doesn't calculate the networking, it would be a nice to have this feature done in the future but it's pretty complex for the current status of the project. 

The motivation of this repo is to have an approximate overall idea regarding your Kubernetes workloads but only related to disk size and ec2 resources.
